name: 'CI/ CD'

on: 
  push:
    branches: [master]
  pull_request:
    

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    env:
      buildVersion: 0.0.0.0 #The initial build version, calculated and updated in the script below
      buildVersion2: 0.0.0.0 #
      taskEnabled: "false"
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v1
    - name: Custom script to create a unique application version number for this build
      run: src/BuildVersion.ps1 -ProjectFile "src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj"
      shell: pwsh
    - name: Set variable test
      run: |
        echo "buildVersion2=1.2.3.4" >> $GITHUB_ENV
    - name: Test variables
      run: |
        echo ${{env.buildVersion}}
        echo ${{env.buildVersion2}}
    - name: Build with dotnet
      if: ${{ env.taskEnabled == 'true' }}
      run: dotnet build src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj --configuration Release
    - name: Test with dotnet
      if: ${{ env.taskEnabled == 'true' }}
      run: dotnet test src/AzurePipelinesToGitHubActionsConverter.Tests/AzurePipelinesToGitHubActionsConverter.Tests.csproj --configuration Release
    - name: Pack with dotnet
      if: ${{ env.taskEnabled == 'true' }}
      run: dotnet pack src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj --configuration Release /p:PackageVersion=${{env.buildVersion}}
    - name: Upload nuget package back to GitHub
      uses: actions/upload-artifact@master
      if: ${{ env.taskEnabled == 'true' }}
      with:
        name: nugetPackage
        path: src/AzurePipelinesToGitHubActionsConverter.Core/bin/Release      

  NuGetPush:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
      
    steps:
    - name: Download nuget package artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: nugetPackage  
    - name: Publish nuget package to nuget.org
      run: dotnet nuget push nugetPackage\*.nupkg --api-key "${{ secrets.GHPackagesToken }}" --source "https://www.nuget.org/"
      shell: pwsh
